### ISSUE TITLE
Hash symbol (#) in filename templates interpreted as comment

### ISSUE THREAD

**Issue by aaduszki** [art-daq/artdaq-database#15]
Following this ticket:
https://github.com/art-framework-suite/fhicl-cpp/issues/12
I open the issue in artdaq_database, as we're not sure where exactly the bug is localized.

**Describe the bug**
In ICARUS, we store our artdaq FHiCL configuration in a DB, which we access using conftool.py. When comparing two versions of our configurations (`Physics_General_Thr400_Majority_5_10_00020` and `Physics_General_Thr400_Majority_5_10_00021`), I discovered the diff output if full of entries like this:
```
32c32
< outputs.testOutputBNB.fileName: '/data/test_daq/data_dl3_fstrmBNB_run%R_%#_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root'
---
> outputs.testOutputBNB.fileName: '/data/test_daq/data_dl3_fstrmBNB_run%R_%#_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root'
```
It appears to me, that the # symbol which is used in art filename templates is interpreted as a comment and is repeatedly appended at the end of the line in each consecutive version of the configuration.

Our software versions:
```
fhiclcpp          v4_15_03        -f Linux64bit+3.10-2.17 -q e20:prof        -z /daq/software/products
artdaq_database   v1_05_08        -f Linux64bit+3.10-2.17 -q e20:prof:s112   -z /daq/software/products
```

**To Reproduce**
```
mkdir 20 21
cd 21
conftool.py exportConfiguration Physics_General_Thr400_Majority_5_10_00021
cd ../20
conftool.py exportConfiguration Physics_General_Thr400_Majority_5_10_00020
diff Physics_General_Thr400_Majority_5_10_/ ../21/Physics_General_Thr400_Majority_5_10_/
```

**If this is a high-priority issue**
This is not a showstopper, but this makes comparing the configurations very difficult, as the diffs are cluttered with the entries like the one above

**Comment by gennadiy-fnal** [comment]
the issue appears to be in fhicl_comments_parser_grammar. 

https://github.com/art-daq/artdaq_database/blob/4aeca1ba5dbca6575af8580c23ae4a1083b59fff/artdaq-database/DataFormats/Fhicl/fhicl_reader.h#L40-L66

**Comment by aaduszki** [comment]
Thank you @gennadiy-fnal and @eflumerf !
