### ISSUE TITLE
Add support for "#includes" before PROLOGs in the db layer.

### ISSUE THREAD

**Issue by eflumerf** [art-daq/artdaq-database#6]
*This issue has been migrated from https://cdcvs.fnal.gov/redmine/issues/20482 (FNAL account required)*
*Originally created by @gennadiy-fnal on 2018-07-30 17:51:41*

----

The db configuration layer does not support having “#includes” before PROLOGs in fhicl files.

**Comment by gennadiy-fnal** [comment]
This is probably something old, so I'll close it for now.
